eureka:
  client:
    register-with-eureka: false


server:
  port: 8080
  # ssl:
  #   enabled: true
  #   key-store: file:/${KEY_RELATIVE_PATH}
  #   key-store-password: ${KEY_PASSWORD}
  #   key-store-type: PKCS12
  #   key-alias: ${KEY_ALIAS}

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://${IP_SERVER}:5173"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: false
      routes:
        - id: integracion-siesa
          uri: 'http://${IP_SERVER}:9090'
          predicates:
            - Path=/api/integracion_siesa/**
          filters:
            - AuthenticationFilter

        - id: remitentes
          uri: 'http://${IP_SERVER}:8070'
          predicates:
            - Path=/api/email/**
          filters:
            - AuthenticationFilter

        - id: integracion-cliente
          uri: 'http://${IP_SERVER}:9090'
          predicates:
            - Path=/api/cliente/**
          filters:
            - AuthenticationFilter

        - id: integracion-planta
          uri: 'http://${IP_SERVER}:9090'
          predicates:
            - Path=/api/planta/**
          filters:
            - AuthenticationFilter

        - id: factura
          uri: 'http://${IP_SERVER}:8060'
          predicates:
            - Path=/api/historico_facturas/**
          filters:
            - AuthenticationFilter

        - id: operador
          uri: 'http://${IP_SERVER}:9091'
          predicates:
            - Path=/api/operador/**
          filters:
            - AuthenticationFilter

        - id: tarifaoperador
          uri: 'http://${IP_SERVER}:9091'
          predicates:
            - Path=/api/tarifaoperador/**
          filters:
            - AuthenticationFilter

        - id: facturacion-especial
          uri: 'http://${IP_SERVER}:9081'
          predicates:
            - Path=/api/facturacion_especial/**
          filters:
            - AuthenticationFilter

        - id: generation
          uri: 'http://${IP_SERVER}:9092'
          predicates:
            - Path=/api/generacion/**
          filters:
            - AuthenticationFilter

        - id: security
          uri: 'http://${IP_SERVER}:8050'
          predicates:
            - Path=/api/**,/oauth2/authorization/**,/login/oauth2/**
          filters:
            - AddRequestHeader=X-Forwarded-Host, ${IP_SERVER}:8080
            - AddRequestHeader=X-Forwarded-Port, 8080
            - AddRequestHeader=X-Forwarded-Proto, https

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

api:
  secret: ${SECRET_KEY}