server:
  port: 9090
  # ssl:
  #   enabled: true
  #   key-store: file:/${KEY_RELATIVE_PATH}
  #   key-store-password: ${KEY_PASSWORD}
  #   key-store-type: PKCS12
  #   key-alias: ${KEY_ALIAS}

spring:
  application:
    name: msvc-integracion
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SQL_URL}
    username: ${SQL_USER_NAME}
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect

api:
  connikey: ${CONNI_KEY}
  conniToken: ${CONNI_TOKEN}
  IP_PROTOCOL: ${IP_PROTOCOL_SERVE}

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
      apache:
        http: DEBUG

eureka:
  instance:
    hostname: ${IP_SERVER}
  client:
    service-url:
      defaultZone: ${IP_PROTOCOL_SERVE}:8761/eureka/
